self.addEventListener('install',event=>{
  event.waitUntil(
    caches.open('arena-duel-v1').then(c=>c.addAll([
      './',
      './index.html',
      './manifest.webmanifest'
    ]))
  );
});
self.addEventListener('fetch',event=>{
  event.respondWith(
    caches.match(event.request).then(resp=>resp||fetch(event.request))
  );
});
